/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.DataContainer;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author BenMorrisRains
 */
public class TopLevelMenu extends javax.swing.JFrame {

    DataContainer datamodel = new DataContainer();
    
    /**
     * Creates new form TopLevelMenu
     */
    public TopLevelMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        viewCatalog = new javax.swing.JButton();
        inputButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileLabel = new javax.swing.JMenu();
        saveToLibrary = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        importCatalog = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bebas Neue", 0, 36)); // NOI18N
        jLabel1.setText("Home Library Catalog ");

        viewCatalog.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        viewCatalog.setText("View Catalog");
        viewCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCatalogActionPerformed(evt);
            }
        });

        inputButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        inputButton.setText("Input Book Information");
        inputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputButtonActionPerformed(evt);
            }
        });

        fileLabel.setText("File");
        fileLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileLabelActionPerformed(evt);
            }
        });

        saveToLibrary.setText("Save to Library");
        saveToLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToLibraryActionPerformed(evt);
            }
        });
        fileLabel.add(saveToLibrary);

        exit.setText("Quit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        fileLabel.add(exit);

        jMenuBar1.add(fileLabel);

        jMenu1.setText("Books");

        importCatalog.setText("Import Catalog");
        importCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importCatalogActionPerformed(evt);
            }
        });
        jMenu1.add(importCatalog);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCatalogActionPerformed
        // TODO add your handling code here:
        BookInfoReportForm viewBookForm = new BookInfoReportForm(datamodel); 
        viewBookForm.setSize(750,425); 
        viewBookForm.setVisible(true);
        
    }//GEN-LAST:event_viewCatalogActionPerformed

    private void inputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputButtonActionPerformed
        // TODO add your handling code here:
        
        InputBookInfo addBookForm = new InputBookInfo(datamodel); 
        addBookForm.setSize(425, 375); 
        addBookForm.setVisible(true);
    }//GEN-LAST:event_inputButtonActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void saveToLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToLibraryActionPerformed
        // TODO add your handling code here:
        String menuItemClicked = evt.getActionCommand(); 
        if (!menuItemClicked.equals("Save to Library")) { 
            
        }else {
          
            
                datamodel.writeTextFile();
           
           
        }
    }//GEN-LAST:event_saveToLibraryActionPerformed

    private void fileLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileLabelActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_fileLabelActionPerformed

    private void importCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importCatalogActionPerformed
        // TODO add your handling code here:
         String menuItemClicked = evt.getActionCommand();
        if (menuItemClicked.equals("Import Catalog")) {
        }
            datamodel.readTextFile();
            //datamodel.readSerializedFile();
    }//GEN-LAST:event_importCatalogActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu fileLabel;
    private javax.swing.JMenuItem importCatalog;
    private javax.swing.JButton inputButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem saveToLibrary;
    private javax.swing.JButton viewCatalog;
    // End of variables declaration//GEN-END:variables

public static void main(String[] args) {
    TopLevelMenu topmenu = new TopLevelMenu();
    topmenu.setVisible(true); 
}


}
